German Translation
jamulussoftware/jamulussoftware.github.io pull request #11
Opened 2020-10-27 16:40 UTC by SmuSmu

2020-10-27 17:34 UTC, ann0see requested changes
Thanks again for your translation. I'd suggest to use a translation software like deepl, since in your translation I spotted some inconsistencies like du/Sie etc.

2020-10-27 17:34 UTC, ann0see commented on wiki/de/de-Command-Line-Options.md
> +lang: "en"
Hi SmuSmu,

Thank you for your traslation! You need to change this to lang: "de". (Sonst wird die Seite als Englisch markiert )

2020-10-27 17:34 UTC, ann0see commented on wiki/de/de-Command-Line-Options.md
> +Sie können alle verfügbaren Optionen zur aktuellen Version von Jamulus über den Parameter `-h` erfahren.
I used "du", not "Sie" since I think it sounds better for a software like Jamulus.

2020-10-27 17:34 UTC, ann0see commented on wiki/de/de-Command-Line-Options.md
> +lang: "en"
I'd suggest you to use a translation software like https://www.deepl.com/translator. The quality is quite good.

2020-10-27 17:34 UTC, ann0see commented on wiki/de/de-Command-Line-Options.md
> +Um zum Beispiel bei Windows die Rekorderfunktion mit dem `-R` Argument zu aktivieren : Rechtsklick auf die Jamulus Verknüpfung und wählen Sie "Eigenschaften" > Ziel. Füge dann die nötigen Argumente z
"Klicke mit der rechten Maustaste auf [...] und wähle [...]" sounds more natural then "Rechtsklick auf die Jamulus Verknüpfung" for me.

2020-10-28 15:19 UTC, SmuSmu reviewed
Thanks for your Input I changed additional some small things

2020-10-28 17:51 UTC, ann0see commented
Ok. That looks good now. I will merge it.

2020-10-28 17:52 UTC, merged

2020-10-28 20:02 UTC, SmuSmu commented
Could you add an hacktoberfest-accepted Label plz 🤗

2020-10-28 20:03 UTC, ann0see commented
What do you mean by that?

2020-10-28 20:10 UTC, SmuSmu commented
https://hacktoberfest.digitalocean.com/hacktoberfest-update

2020-10-28 20:21 UTC, ann0see commented
Ok. Done that. Good luck ;-).

2020-10-28 20:24 UTC, ann0see commented
If you want, you can also try to open a PR on the official jamulus repo where you add the new website.