Add basic android guide
jamulussoftware/jamulussoftware.github.io pull request #297
Opened 2021-02-14 19:01 UTC by ann0see

Solves #264 I added this guide but also made clear that it's in early beta. I think adding this (although it seems to be in early beta) does give a big value to users.

2021-02-14 19:08 UTC, pljones commented
I'm not sure I'd go as far as "early beta".  It's more "proof of concept", in my view.  "Beta" tends to mean there's effort being made in bringing about a release and then maintaining it.  I don't see that happening.

2021-02-14 19:19 UTC, ann0see commented
Fair point. I think once this is on the website, some people will jump in and maybe try to bring it further. Thanks to nefarius, we now have a working and install-able version now, so it will be much more accessible. iOS is more of a proof of concept (headless server only) while android is accessible and to some extent works.

2021-02-14 20:05 UTC, pljones commented
Well, "alpha".  But even that implies it's got some development effort behind it.  I'd leave it at proof of concept until someone does step up to get involved.

2021-02-14 20:06 UTC, ann0see commented
Ok so let's change it to proof of concept or PoC for the button?

2021-02-14 21:33 UTC, ann0see commented
Ok. @pljones done.

2021-02-14 21:51 UTC, pljones approved these changes

2021-02-14 22:03 UTC, gilgongo approved these changes

2021-02-14 22:55 UTC, nefarius2001 requested changes

2021-02-14 22:55 UTC, nefarius2001 commented on wiki/en/en-Installation-for-Android.md
> +1. Allow the installation of apps from unknown sources (look in Settings>Security).
maybe add a hint, that this can vary for devices and OS-versions.

2021-02-14 22:55 UTC, nefarius2001 commented on wiki/en/en-Installation-for-Android.md
> +1. Download the APK from the [GitHub release page](https://github.com/corrados/jamulus/releases/tag/latest)
after download, the apk needs to be installed. In my case: open list of downloads in chrome, klick on the filename of APK, confirm that I want to install.

2021-02-15 07:04 UTC, ann0see commented
@nefarius2001 could you please review again? I‘ve added your proposal.

2021-02-16 18:12 UTC, merged