German translation for v3_7_0
jamulussoftware/jamulussoftware.github.io pull request #347
Opened 2021-03-03 21:41 UTC by ann0see

#343

2021-03-04 22:01 UTC, hoffie requested changes
I've checked the diff between #343 and #347. One really minor duplicate word, after that, it's good to go? :)

2021-03-04 22:01 UTC, hoffie commented on wiki/de/de-Installation-for-Windows.md
> +1. **Richte deine Soundkarte ein**. Wenn du Jamulus installiert hast, musst du deine Audio-Hardware einrichten. Falls du ASIO4ALL nutzt, schau dir die [Einrichtung](#asio4all-einrichten) an und/oder
```suggestion
1. **Richte deine Soundkarte ein**. Wenn du Jamulus installiert hast, musst du deine Audio-Hardware einrichten. Falls du ASIO4ALL nutzt, schau dir die [Einrichtung](#asio4all-einrichten) und/oder das [Hardware-Setup](Hardware-Setup) an.
```

2021-03-05 07:45 UTC, ann0see commented
I think there's still a missing link to the onboarding page>connect to a server on the Windows page.

2021-03-05 11:15 UTC, ann0see commented on wiki/de/de-Installation-for-Windows.md
> +**Tipp:** Richte deine Soundkarte ein, wenn du mit einem Server verbunden bist Das erleichtert dir das Setup, da du dann mit deinem Instrument oder deiner Stimme testen kannst, ob alles richtig einge
@ann0see TODO: link onboarding!

2021-03-05 12:19 UTC, ann0see commented
Should be done now. @gilgongo since the contributing document probably will be changed soon, should I still translate it?

2021-03-05 12:33 UTC, merged