Add Presonus studio 24C audio interface to known good devices, add so…
jamulussoftware/jamulussoftware.github.io pull request #412
Opened 2021-04-02 10:16 UTC by pieterbos

…me RTL measurements and change one 'should work' to 'works

Fixes #372

# Does this need translation?

- [x] Yes 
- [ ] No 

# Changes

- Added Presonus Studio 24c as known good hardware for Mac and Windows, with RTL measurement in windows
- Changed Focusrite Scarlett on Mac OS X to works great, plus latency measurement
- Added latency measurement to Behringer UMC202HD on mac OS X
- Added latency measurement plus more working kernel versions on HifiBerry Dac+ ADC (Pro)

This would benefit from translation, but the original page is not translated, so not sure to what branch this should go.
Maybe the latency measurements should be in a separate table, to keep things more readable?

2021-04-04 09:15 UTC, gilgongo commented
KB articles don't require translation and are not part of the translation process for the rest of the site. But if anyone wants to do them that's fine. Ignore otherwise.

2021-04-04 09:21 UTC, gilgongo commented
Maybe we should add a line to @hoffie release process stuff to clarify how the KB works? The original idea was to have a place on the website that would replace the old wiki, where anyone could just whack something up without having to concern the rest of the project work. Having these PRs handled as part of all the other stuff we track isn't the idea.

2021-04-05 08:05 UTC, ann0see requested changes
Looks good. It should go to release. If you want to translate it, feel free to do so. But you'll need to be quick and translate every edit to not be out of sync of the English translation

2021-04-05 08:30 UTC, gilgongo commented
I thin for KB stuff, we just publish it without the need to for any review. Part of the point of the KB is that it's for peripheral information maintained by people who aren't the main team.

2021-04-05 08:32 UTC, merged