Update fr web translation for 3.8.1
jamulussoftware/jamulussoftware.github.io pull request #623
Opened 2021-09-18 22:24 UTC by jujudusud

Fixes #613

2021-09-19 05:41 UTC, ignotus666 commented
Hi @jujudusud, thanks! Just a couple of things:

- This is my fault for not explicitly pointing it out beforehand: please do not use QtLinguist. It messes up the line wrapping and adds a load of unneeded information to the file header. See "Suggested .po file editors" [here](https://github.com/jamulussoftware/jamuluswebsite/tree/next-release/_translator-files).
- The following files have also changed: `/1-index.html` and `_data/en/navigation.yml`. For the next release all these files that are outside `/wiki/en` will also be included as .po files, so tracking changes to them will be easier - I just didn't have time to make the necessary changes for this release.

To solve the wrapping issue: just run `po4a-update-templates-sh` locally and push the changes to your branch. The extra info in the header will still remain but that's not serious.

2021-09-20 05:23 UTC, ignotus666 commented
I see that you now opened the files in Poedit, but the wrong wrapping is still there. Did you follow the instructions for Poedit [here](https://github.com/jamulussoftware/jamuluswebsite/tree/next-release/_translator-files)? You have to uncheck "wrap at" in the advanced tab. Again, the quickest solution is to run po4a-update-templates.sh locally.

2021-09-20 06:01 UTC, jujudusud commented
I have followed the instructions for poedit but have not yet used the script to make the files conform.
I have to deal with the links first, some of which are untranslated.

2021-09-24 08:44 UTC, ignotus666 commented
@jujudusud sorry about that commit I pushed to your repo! That was a bizarre accident. Reverted.

2021-09-24 14:04 UTC, ignotus666 requested changes
Here's the review - my bad

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Client-Troubleshooting.po
> +msgstr "Dans certains cas, il se peut que ce soit votre fournisseur d'accès qui bloque l'utilisation de Jamulus. Voir la note sur la [page de dépannage du serveur](Server-Troubleshooting#nobody-can-c
This should be left in French

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/QOS-Windows.po
> +msgstr "Dans la boîte de recherche à côté du menu Démarrer, tapez : Local Group Policy Editor (entrer)<br> Dans la nouvelle fenêtre, (cliquer) sur l'icône du menu pour afficher le troisième panneau A
An update after the release will fix the wrapping in segments like this one. It should come out ok in the translation in any event. 

Edit: Actually, it won't, because the line breaks (\n) have been removed. Still, the final document comes out fine - it's just very ugly when editing it.

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Client-Troubleshooting.po
> +msgstr "Dans certains cas, il se peut que ce soit votre fournisseur d'accès qui bloque l'utilisation de Jamulus. Voir la note sur la [page de dépannage du serveur](Server-Troubleshooting#Personne-ne-
These links to a specific paragraph can't start with a capital letter, otherwise they won't work properly - should be '**p**ersonne-ne-peut...'

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Getting-Started.po
> +msgstr "Une fois connecté à un serveur, assurez-vous que vous pouvez vous entendre correctement et corrigez tout problème de volume d'entrée ou autre. Et bien sûr, vérifiez que vous êtes également ca
Capital letter in link after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Installation-for-Windows.po
> +msgstr "**Astuce : ** Configurez votre carte son pendant que vous êtes [connecté à un serveur] (Getting-Started#Se-connecter-à-un-serveur-et-tester-son-son) pour entendre votre instrument ou votre vo
Capital letter after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "De nombreuses personnes attribuent au serveur des problèmes qui sont en fait des problèmes du _client_. Cela dépend en grande partie du matériel, de la configuration des clients, des réseaux
Capital letter after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "Si vous prévoyez de jouer régulièrement avec les mêmes personnes, **il vous est fortement conseillé** de vous assurer d'abord que chaque membre du groupe est configuré pour utiliser Jamulus c
Capital letter

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "Pour exécuter un serveur privé à la maison, vous devez effectuer une [redirection de port](#running-a-private-server) sur votre routeur. Lorsque vous exécutez un serveur privé, la redirection
Translation missing after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "Par défaut, vous utilisez un serveur privé et vous devez [lire ces instructions](#running-a-private-server) pour que d'autres personnes puissent se connecter à vous dans ce mode."
Translation missing after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "Laissez ce champ vide, sauf si vous devez inscrire votre serveur dans un [annuaire privé](#3-directory)"
Translation missing after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "`-e` ou `--directoryserver` Enregistrer le serveur sur un annuaire (par exemple pour définir son genre (voir aussi `-o`)). Voir [types de serveurs](#server-types) pour plus d'informations.\n"
Translation missing after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "`-P` ou `--delaypan`       Démarrer avec le panoramique du délai activé Voir [notes](#delay-panning))\n"
Translation missing after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "`--serverpublicip`  L'adresse IP publique du serveur s'il est connecté à un annuaire derrière le même NAT. Voir [Notes sur les serveurs d'annuaire](#points-to-note-about-directories)\n"
Translation missing after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Server-Linux.po
> +msgstr "La configuration minimale suivante est requise pour [exécuter un serveur public](Running-a-Server#Types-de-serveurs) :"
Capital letter after #

2021-09-24 14:04 UTC, ignotus666 commented on _translator-files/po/fr/Server-Troubleshooting.po
> +msgstr "Si vous êtes enregistré correctement (vous pouvez le voir [ici](https://explorer.jamulus.io/)) et que vous ou vos amis ne voyez pas votre serveur, vous pouvez attendre, ou démarrer votre clie
Capital letter after #

2021-09-25 17:24 UTC, jujudusud commented on _translator-files/po/fr/Client-Troubleshooting.po
> +msgstr "Dans certains cas, il se peut que ce soit votre fournisseur d'accès qui bloque l'utilisation de Jamulus. Voir la note sur la [page de dépannage du serveur](Server-Troubleshooting#nobody-can-c
done

2021-09-25 17:25 UTC, jujudusud commented on _translator-files/po/fr/Client-Troubleshooting.po
> +msgstr "Dans certains cas, il se peut que ce soit votre fournisseur d'accès qui bloque l'utilisation de Jamulus. Voir la note sur la [page de dépannage du serveur](Server-Troubleshooting#Personne-ne-
done

2021-09-25 17:28 UTC, jujudusud commented on _translator-files/po/fr/Getting-Started.po
> +msgstr "Une fois connecté à un serveur, assurez-vous que vous pouvez vous entendre correctement et corrigez tout problème de volume d'entrée ou autre. Et bien sûr, vérifiez que vous êtes également ca
done

2021-09-25 17:30 UTC, jujudusud commented on _translator-files/po/fr/Installation-for-Windows.po
> +msgstr "**Astuce : ** Configurez votre carte son pendant que vous êtes [connecté à un serveur] (Getting-Started#Se-connecter-à-un-serveur-et-tester-son-son) pour entendre votre instrument ou votre vo
done

2021-09-25 17:42 UTC, jujudusud commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "De nombreuses personnes attribuent au serveur des problèmes qui sont en fait des problèmes du _client_. Cela dépend en grande partie du matériel, de la configuration des clients, des réseaux
done

2021-09-25 17:43 UTC, jujudusud commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "Pour exécuter un serveur privé à la maison, vous devez effectuer une [redirection de port](#running-a-private-server) sur votre routeur. Lorsque vous exécutez un serveur privé, la redirection
done

2021-09-25 17:45 UTC, jujudusud commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "Laissez ce champ vide, sauf si vous devez inscrire votre serveur dans un [annuaire privé](#3-directory)"
done

2021-09-25 17:46 UTC, jujudusud commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "`-e` ou `--directoryserver` Enregistrer le serveur sur un annuaire (par exemple pour définir son genre (voir aussi `-o`)). Voir [types de serveurs](#server-types) pour plus d'informations.\n"
done

2021-09-25 17:46 UTC, jujudusud commented on _translator-files/po/fr/Running-a-Server.po
> +msgstr "`-P` ou `--delaypan`       Démarrer avec le panoramique du délai activé Voir [notes](#delay-panning))\n"
done

2021-09-25 17:48 UTC, jujudusud commented on _translator-files/po/fr/Server-Linux.po
> +msgstr "La configuration minimale suivante est requise pour [exécuter un serveur public](Running-a-Server#Types-de-serveurs) :"
done

2021-09-25 17:50 UTC, jujudusud commented on _translator-files/po/fr/Server-Troubleshooting.po
> +msgstr "Si vous êtes enregistré correctement (vous pouvez le voir [ici](https://explorer.jamulus.io/)) et que vous ou vos amis ne voyez pas votre serveur, vous pouvez attendre, ou démarrer votre clie
done

2021-09-25 19:46 UTC, ignotus666 approved these changes

2021-09-25 19:47 UTC, ignotus666 commented
Looks good to me, thanks!

2021-09-25 22:47 UTC, jujudusud commented
> Looks good to me, thanks!

Thanks for you the review ! :-)

2021-09-28 13:31 UTC, ignotus666 commented
@jujudusud Sorry about this but at the beginning of `Privacy-Statement.md` there is an untranslated sentence. It probably got marked as translated (inserting the English sentence) by mistake when I converted everything into .po files, which is why you didn't see it. With that, your translation should be 100% :)

2021-10-01 17:03 UTC, merged