Update fr web translation for 3.9.0
jamulussoftware/jamulussoftware.github.io pull request #780
Opened 2022-07-13 17:20 UTC by jujudusud

**Short description of changes**
Translation of the website in french.

**Context: Fixes an issue? Related issues**
Fixes: #776

**Status of this Pull Request**
In progress.

**What is missing until this pull request can be merged?**
- [ ] All the po file are fully tranlsated.

**Does this need translation?**
No

## Checklist
- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

2022-07-14 10:52 UTC, trebmuh commented on _translator-files/po/fr/Installation-for-Windows.po
manque un accent sur "acquérir"

2022-07-14 10:53 UTC, trebmuh commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr " **Miroir 2:** [SourceForge](https://sourceforge.net/projects/llcon/files/latest/download)\n"
manque un espace après le "2"

2022-07-14 10:54 UTC, trebmuh commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr "Pour macOS Mojave (10.14 ou inférieurs) veuillez [télécharger la version les systèmes historiques]({{ site.download_root_link }}{{ site.download_file_names.mac-legacy }})"
proposition : "télécharger une ancienne version"

2022-07-14 14:52 UTC, jujudusud commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr "Pour macOS Mojave (10.14 ou inférieurs) veuillez [télécharger la version les systèmes historiques]({{ site.download_root_link }}{{ site.download_file_names.mac-legacy }})"
J'ai un problème ici parce que : 
- ce n'est pas une ancienne version du logiciel mais la dernière version officielle,
- c'est le système d'exploitation qui est "historique" ou plutôt plus supporté par le développeur.
Je vais réfléchir un peu avant d'agir. :-)

2022-07-14 15:03 UTC, jujudusud commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr "Pour macOS Mojave (10.14 ou inférieurs) veuillez [télécharger la version les systèmes historiques]({{ site.download_root_link }}{{ site.download_file_names.mac-legacy }})"
je pense que je vais revenir en arrière et utiliser l'ancienne formulation (dont nous avions déjà parlé) :
"Téléchargement pour les systèmes historiques"

2022-07-14 15:11 UTC, jujudusud commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr "Pour macOS Mojave (10.14 ou inférieurs) veuillez [télécharger la version les systèmes historiques]({{ site.download_root_link }}{{ site.download_file_names.mac-legacy }})"
Ok done.

2022-07-14 15:11 UTC, jujudusud commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr " **Miroir 2:** [SourceForge](https://sourceforge.net/projects/llcon/files/latest/download)\n"
done

2022-07-14 15:12 UTC, jujudusud commented on _translator-files/po/fr/Installation-for-Windows.po
done

2022-07-14 20:46 UTC, trebmuh requested changes, later dismissed
:+1:

2022-07-14 20:46 UTC, trebmuh commented on _translator-files/po/fr/Server-Bandwidth.po
> +"| Chaînes | Qualité | Bande passante (pour buffer : 2.67 ms) | Bande passante (pour tampon : 5,33 ms) | Bande passante (pour buffer : 10.67 ms) | Bande passante (pour buffer : 21.33 ms) |\n"
Note : il reste des "buffer" ici

2022-07-14 20:46 UTC, trebmuh commented on _translator-files/po/fr/Server-Bandwidth.po
> +"Il y en a un en amont (le musicien envoie au Serveur) et un en aval (le serveur renvoie le mix au musicien)\n"
Pourquoi une majuscule à "serveur" ?

2022-07-14 20:48 UTC, trebmuh commented on _translator-files/po/fr/Installation-for-Macintosh.po
> +msgstr "Pour macOS Mojave (10.14 ou inférieurs) veuillez [télécharger la version les systèmes historiques]({{ site.download_root_link }}{{ site.download_file_names.mac-legacy }})"
OK, j'avais mal compris la phrase originelle. Merci.
"Télécharger la version pour les systèmes historiques" est bien alors. "Télécharger la version pour les anciens systèmes" fonctionnent aussi.

2022-07-15 13:04 UTC, jujudusud commented on _translator-files/po/fr/Server-Bandwidth.po
> +"| Chaînes | Qualité | Bande passante (pour buffer : 2.67 ms) | Bande passante (pour tampon : 5,33 ms) | Bande passante (pour buffer : 10.67 ms) | Bande passante (pour buffer : 21.33 ms) |\n"
Merci !

2022-07-15 13:04 UTC, jujudusud commented on _translator-files/po/fr/Server-Bandwidth.po
> +"Il y en a un en amont (le musicien envoie au Serveur) et un en aval (le serveur renvoie le mix au musicien)\n"
Il n'y a pas de raison, je corrige. Merci.

2022-07-16 14:38 UTC, jujudusud commented
I will squash all the commits now.

2022-07-16 16:36 UTC, pljones approved these changes

2022-07-16 17:58 UTC, merged