Update Style-and-Tone.md
jamulussoftware/jamulussoftware.github.io pull request #910
Opened 2023-03-26 17:25 UTC by pljones

**Short description of changes**

Add "Server List" to "Standard terms".

**Context: Fixes an issue? Related issues**

No but see https://github.com/jamulussoftware/jamulus/pull/3017#discussion_r1148594065

**Status of this Pull Request**

To be reviewed.

**What is missing until this pull request can be merged?**

To be reviewed.

**Does this need translation?**

Yes.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I'm sure that this Pull Request goes to the correct branch

2023-03-26 17:28 UTC, pljones commented on contribute/en/Style-and-Tone.md
> +“Server List” This is the list of Servers maintained by a Directory.  A Server registers with a Directory to be _listed_ in that Directory’s server list.
```suggestion
“Server List” This is the list of Servers maintained by a Directory.  A Server registers with a Directory to be _listed_ in that Directory’s _server list_.
```

2023-03-26 18:40 UTC, ignotus666 commented
This doesn't get translated - they're guidelines for writing the original docs in English.

2023-03-26 19:49 UTC, ann0see commented
Agree. Could you please rebase it to release and point the PR to release? We can then publish it directly.

2023-03-26 19:49 UTC, ann0see approved these changes

2023-03-26 19:50 UTC, ann0see requested changes
As above.

2023-03-27 18:00 UTC, closed without merging

2023-03-27 18:19 UTC, pljones commented
Replaced by #911