Translations update from Hosted Weblate
jamulussoftware/jamulussoftware.github.io pull request #955
Opened 2023-08-06 13:10 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Jamulus/Startpage](https://hosted.weblate.org/projects/jamulus/1-index/).

It also includes the following components:

* [Jamulus/Copyright notices](https://hosted.weblate.org/projects/jamulus/copyright-notices/)

* [Jamulus/Software-Manual](https://hosted.weblate.org/projects/jamulus/software-manual/)

* [Jamulus/Include-Shared-Commands](https://hosted.weblate.org/projects/jamulus/include-shared-commands/)

* [Jamulus/Server-Bandwidth](https://hosted.weblate.org/projects/jamulus/server-bandwidth/)

* [Jamulus/Installation-for-Android](https://hosted.weblate.org/projects/jamulus/installation-for-android/)

* [Jamulus/FAQ](https://hosted.weblate.org/projects/jamulus/faq/)

* [Jamulus/Include-Backing-Up](https://hosted.weblate.org/projects/jamulus/include-backing-up/)

* [Jamulus/Tips-Tricks-More](https://hosted.weblate.org/projects/jamulus/tips-tricks-more/)

* [Jamulus/Command-Line-Options](https://hosted.weblate.org/projects/jamulus/command-line-options/)

* [Jamulus/QOS-Windows](https://hosted.weblate.org/projects/jamulus/qos-windows/)

* [Jamulus/Getting-Started](https://hosted.weblate.org/projects/jamulus/getting-started/)

* [Jamulus/Installation-for-Macintosh](https://hosted.weblate.org/projects/jamulus/installation-for-macintosh/)

* [Jamulus/Include-Client-Commands](https://hosted.weblate.org/projects/jamulus/include-client-commands/)

* [Jamulus/Navigation](https://hosted.weblate.org/projects/jamulus/navigation/)

* [Jamulus/Installation-for-iOS](https://hosted.weblate.org/projects/jamulus/installation-for-ios/)

* [Jamulus/Client-Troubleshooting](https://hosted.weblate.org/projects/jamulus/client-troubleshooting/)

* [Jamulus/General strings](https://hosted.weblate.org/projects/jamulus/general/)

* [Jamulus/Contribution](https://hosted.weblate.org/projects/jamulus/contribution/)

* [Jamulus/Server-Troubleshooting](https://hosted.weblate.org/projects/jamulus/server-troubleshooting/)

* [Jamulus/Unregistered-Servers](https://hosted.weblate.org/projects/jamulus/unregistered-servers/)

* [Jamulus/Installation-for-Linux](https://hosted.weblate.org/projects/jamulus/installation-for-linux/)

* [Jamulus/Installation-for-Windows](https://hosted.weblate.org/projects/jamulus/installation-for-windows/)

* [Jamulus/Running-a-Server](https://hosted.weblate.org/projects/jamulus/running-a-server/)

* [Jamulus/Directories](https://hosted.weblate.org/projects/jamulus/directories/)

* [Jamulus/Privacy-Statement](https://hosted.weblate.org/projects/jamulus/privacy-statement/)

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/jamulus/-/1-index/horizontal-auto.svg)

2023-08-06 13:15 UTC, ignotus666 commented on _translator-files/po/nb_NO/Client-Troubleshooting.po
> +msgstr "/wiki/klientproblemløsing"
@comradekingu these links shouldn't be translated.

2023-08-06 13:26 UTC, comradekingu commented
@ignotus666 OK. I suppose flagging those as "read-only" in WL helps avoid the mistake.
https://hosted.weblate.org/user/kingu/ is not an admin, so I can't fix that other than to undo the translations.

2023-08-07 12:41 UTC, jujudusud commented
@ignotus666 :
Can you please answer this question?
https://hosted.weblate.org/translate/jamulus/unregistered-servers/fr/?q=has:comment#comments

2023-08-07 13:00 UTC, jujudusud commented
French Part of the website translation is ready to be merged.

2023-08-07 13:21 UTC, ignotus666 commented
@jujudusud answered!

2023-08-07 13:27 UTC, jujudusud commented
Thanks a lot @ignotus666

2023-08-08 15:19 UTC, henkdegroot commented
All translation for Dutch is included in this PR. Ready to be merged.

2023-08-08 17:36 UTC, trebmuh commented
I had time to review and fix the website changes.
It's all good for French now.

2023-08-10 20:53 UTC, ann0see requested changes

2023-08-10 20:53 UTC, ann0see commented on _translator-files/po/de/Running-a-Server.po
> -msgstr "Dies ist die Standardeinstellung, wenn du einen Server zum ersten Mal startest. Unregistrierte/private Server werden nicht in Verzeichnissen aufgeführt, so dass nur Musiker, die die Adresse d
This was correct German.

2023-08-14 21:31 UTC, ann0see approved these changes
German is ok too.

2023-08-14 21:31 UTC, merged