Translations update from Hosted Weblate
jamulussoftware/jamulussoftware.github.io pull request #965
Opened 2023-08-24 12:52 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Jamulus/Startpage](https://hosted.weblate.org/projects/jamulus/1-index/).

It also includes the following components:

* [Jamulus/Navigation](https://hosted.weblate.org/projects/jamulus/navigation/)

* [Jamulus/Installation-for-Macintosh](https://hosted.weblate.org/projects/jamulus/installation-for-macintosh/)

* [Jamulus/Copyright notices](https://hosted.weblate.org/projects/jamulus/copyright-notices/)

* [Jamulus/Include-Backing-Up](https://hosted.weblate.org/projects/jamulus/include-backing-up/)

* [Jamulus/Server-Bandwidth](https://hosted.weblate.org/projects/jamulus/server-bandwidth/)

* [Jamulus/Software-Manual](https://hosted.weblate.org/projects/jamulus/software-manual/)

* [Jamulus/FAQ](https://hosted.weblate.org/projects/jamulus/faq/)

* [Jamulus/Server-Troubleshooting](https://hosted.weblate.org/projects/jamulus/server-troubleshooting/)

* [Jamulus/Include-Shared-Commands](https://hosted.weblate.org/projects/jamulus/include-shared-commands/)

* [Jamulus/Installation-for-Android](https://hosted.weblate.org/projects/jamulus/installation-for-android/)

* [Jamulus/QOS-Windows](https://hosted.weblate.org/projects/jamulus/qos-windows/)

* [Jamulus/Command-Line-Options](https://hosted.weblate.org/projects/jamulus/command-line-options/)

* [Jamulus/Installation-for-iOS](https://hosted.weblate.org/projects/jamulus/installation-for-ios/)

* [Jamulus/Tips-Tricks-More](https://hosted.weblate.org/projects/jamulus/tips-tricks-more/)

* [Jamulus/Getting-Started](https://hosted.weblate.org/projects/jamulus/getting-started/)

* [Jamulus/Client-Troubleshooting](https://hosted.weblate.org/projects/jamulus/client-troubleshooting/)

* [Jamulus/Include-Client-Commands](https://hosted.weblate.org/projects/jamulus/include-client-commands/)

* [Jamulus/General strings](https://hosted.weblate.org/projects/jamulus/general/)

* [Jamulus/Contribution](https://hosted.weblate.org/projects/jamulus/contribution/)

* [Jamulus/Unregistered-Servers](https://hosted.weblate.org/projects/jamulus/unregistered-servers/)

* [Jamulus/Installation-for-Linux](https://hosted.weblate.org/projects/jamulus/installation-for-linux/)

* [Jamulus/Installation-for-Windows](https://hosted.weblate.org/projects/jamulus/installation-for-windows/)

* [Jamulus/Running-a-Server](https://hosted.weblate.org/projects/jamulus/running-a-server/)

* [Jamulus/Directories](https://hosted.weblate.org/projects/jamulus/directories/)

* [Jamulus/Privacy-Statement](https://hosted.weblate.org/projects/jamulus/privacy-statement/)

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widget/jamulus/1-index/horizontal-auto.svg)

2023-08-24 12:56 UTC, ann0see requested changes

2023-08-24 12:56 UTC, ann0see commented on _translator-files/po/ko_KR/Unregistered-Servers.po
> +msgstr "{% include breadcrumb.html root=\"더보기\" branch1=\"서버 관리\" branch1-url=\"서버 실행\" %}"
This is wrong! The URL must not be translated. Otherwise we'd have a broken link!

2023-08-25 18:09 UTC, pljones commented on _translator-files/po/ko_KR/Unregistered-Servers.po
> +msgstr "{% include breadcrumb.html root=\"더보기\" branch1=\"서버 관리\" branch1-url=\"서버 실행\" %}"
Looks like you fixed it?  Can it go into 3.10.0?

2023-08-25 18:43 UTC, ann0see commented on _translator-files/po/ko_KR/Unregistered-Servers.po
> +msgstr "{% include breadcrumb.html root=\"더보기\" branch1=\"서버 관리\" branch1-url=\"서버 실행\" %}"
Yes. We'll still need to check it.

2023-08-25 20:08 UTC, ann0see approved these changes
Ok. After looking through the diff - it seems to be ok now.

2023-08-31 10:58 UTC, ann0see commented on _translator-files/po/es/Running-a-Server.po
> -"PO-Revision-Date: 2023-08-18 06:52+0000\n"
@ignotus666 please have a look at this.

2023-08-31 11:01 UTC, ann0see commented on _translator-files/po/ko_KR/FAQ.po
> +msgstr "다른 뮤지션들과 함께 제 시간에 연주할 수 있는지 여부는 주로 사운드 신호의 레이턴시(딜레이) 얼마나 되는지, 그리고 모두가 [황금률](/wiki/Client-Troubleshooting#you-all-sound-ok-but-its-difficult-to-keep-together)을 따르고 있는지 여부에 따라 달라집니다. 50ms보다 훨씬
Just as quick note - the links will not be broken, but the anchor just fail. I'm unsure how the actual ID would look like for non ASCII headlines.

2023-08-31 11:04 UTC, ann0see commented on _translator-files/po/ko_KR/Running-a-Server.po
> +"\t<img src=\"{% include img/en-screenshots/diagram-reg-server.inc %}\" loading=\"lazy\" alt=\"Jamulus 등록된 서버 내의 클라이언트 간 연결 다이어그램\">\n"
If we have ko_KR screenshots this would be nice. I'd always prefer not to use the screenshots as includes.

2023-08-31 11:07 UTC, ann0see commented on _translator-files/po/ko_KR/Tips-Tricks-More.po
> +"<?php\n"
The script should really go into the KB...

2023-08-31 11:07 UTC, ann0see reviewed
Looks ok. Please review and I'll soon merge it.

2023-08-31 18:14 UTC, merged